# Run inverseMatrix.cpp
inverseMatrix: inverseMatrix.cpp
	/opt/opencilk/bin/clang++ -fopencilk -O3 inverseMatrix.cpp -o inverseMatrix

# Run closestPairs.cpp
closestPairs: closestPairs.cpp
	/opt/opencilk/bin/clang++ -fopencilk -O3 closestPairs.cpp -o closestPairs

# Clean
clean:
	rm -f inverseMatrix closestPairs